name: A workflow for my Hello World file
on:
  pull_request_review:
    types:
    - submitted
    branches:
    - master
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - run: date && whoami
